In [1]:
#Henry Kroll
#ITS 520
#Fall 2022
#NumPy Problems

In [2]:
import numpy as np

In [3]:
#1

a = np.zeros((3,4))
b = np.ones((5,4))
c = np.vstack((a, b))

print(c)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
#2

a = np.arange(1,11)
b = a.copy()
b = np.insert(b,0,0)
b = np.delete(b, [-1])

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]


In [14]:
#3
A = np.array(([1,2,3],[4,5,6],[7,8,9]))
M = np.array(([0,0,0],[1,0,0],[1,1,0]))

New_x = A * M

print("A")
print(A)
print("M")
print(M)
print("New_x")
print(New_x)


A
[[1 2 3]
 [4 5 6]
 [7 8 9]]
M
[[0 0 0]
 [1 0 0]
 [1 1 0]]
New_x
[[0 0 0]
 [4 0 0]
 [7 8 0]]
