In [1]:
#Henry Kroll
#ITS 520
#Fall 2022
#NumPy Problems

In [2]:
import numpy as np

In [3]:
#1

#For this question, I would consider an 8x4 matrix to be 8 numbers wide and 4 numbers tall, 
#but I wanted to go as literal to the wording of the question as possible. 
#Had I wanted to make the inverse of this, I would swap the input values (i.e. 4,3 instead of 3,4)
#and used hstack instead of vstack to achieve this. 
a = np.zeros((3,4))
b = np.ones((5,4))
c = np.vstack((a, b))

print(c)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
#2
a = np.arange(1,11)
b = a.copy()
b = np.insert(b,0,0)
b = np.delete(b, [-1])

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#3
x = np.